name = "vrc-world-ai-services"
main = "src/index.js"
compatibility_date = "2026-04-01"
keep_vars = true

[[kv_namespaces]]
binding = "STATE_KV"
id = "d0ec26994ae64e148cbb6733a11d517e"
preview_id = "d0ec26994ae64e148cbb6733a11d517e"

[[durable_objects.bindings]]
name = "TRANSLATION_COORDINATOR"
class_name = "TranslationCoordinator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TranslationCoordinator"]
