name = "world-ai-services"
main = "src/index.js"
compatibility_date = "2026-04-01"

[[kv_namespaces]]
binding = "WorldAIService"
id = "d0ec26994ae64e148cbb6733a11d517e"
preview_id = "d0ec26994ae64e148cbb6733a11d517e"

[vars]
AI_PROVIDER_MODE = "result-json"
AI_TIMEOUT_MS = "10000"
